-- CreateTable
CREATE TABLE "restaurant_settings" (
    "id" TEXT NOT NULL,
    "restaurant_name" TEXT NOT NULL DEFAULT 'Al Manzil',
    "tagline" TEXT,
    "phone" TEXT,
    "address" TEXT,
    "logo_url" TEXT,
    "open_time" TEXT NOT NULL DEFAULT '07:00',
    "close_time" TEXT NOT NULL DEFAULT '23:00',
    "timezone" TEXT NOT NULL DEFAULT 'Asia/Dubai',
    "total_tables" INTEGER NOT NULL DEFAULT 10,
    "default_capacity" INTEGER NOT NULL DEFAULT 4,
    "vat_rate" DECIMAL(5,4) NOT NULL DEFAULT 0.05,
    "currency" TEXT NOT NULL DEFAULT 'AED',
    "default_prep_time_mins" INTEGER NOT NULL DEFAULT 15,
    "bookings_enabled" BOOLEAN NOT NULL DEFAULT true,
    "slot_duration_mins" INTEGER NOT NULL DEFAULT 30,
    "walk_in_buffer" INTEGER NOT NULL DEFAULT 3,
    "peak_hours_enabled" BOOLEAN NOT NULL DEFAULT true,
    "peak_start" TEXT NOT NULL DEFAULT '19:00',
    "peak_end" TEXT NOT NULL DEFAULT '22:00',
    "no_show_window_off_peak" INTEGER NOT NULL DEFAULT 20,
    "no_show_window_peak" INTEGER NOT NULL DEFAULT 5,
    "max_booking_days_ahead" INTEGER NOT NULL DEFAULT 7,
    "require_login_to_book" BOOLEAN NOT NULL DEFAULT true,
    "reminders_enabled" BOOLEAN NOT NULL DEFAULT false,
    "reminder_mins_before" INTEGER NOT NULL DEFAULT 60,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "restaurant_settings_pkey" PRIMARY KEY ("id")
);
